### ISSUE TITLE
Song randomly disappears from playlist after some time outside of the app.

### ISSUE THREAD

**Issue by rizwan146** [ECE493-Group5/adjustable-audio#114]
Steps to reproduce:

Queue a song into the playlist but don't play it.
Exit from the app to the home screen.
Wait about 30 seconds to a minute.
Open up the app again. Notice that song disappears from the playlist.
Now try adding a song again to the playlist.
Notice that application crashes.

The reason the application crashes is because mediaPlayer is set to null in the adapter. This implies that the MusicService calls "onDestroy()" for some reason. More investigation is required.

**Comment by atyrrell1** [comment]
https://developer.android.com/reference/android/app/Service.html#ProcessLifecycle

I’ll look more into it tomorrow morning but a possible cause can be heavy
memory consumption.

**Comment by atyrrell1** [comment]
Potentially figured it out. In both the MediaPlayer and Settings Fragments call "musicServiceInteractor.disconnect()", in their onStop Methods which are called if we close the app on that fragment. Since the music service has nothing connected to it for a while, it disconnects (according to the doc). Moving the line of code to the onDestroy() methods for both of these solves this issue

**Comment by atyrrell1** [comment]
Additionally, startService() does not create the music service. I think the music service is created when the MusicServiceInteractor is initiated in MediaPlayerFragment
